### PR TITLE
Remove extra double-quote

### PR DESCRIPTION
**Pull request by drbyte**

### CODE REVIEW

**Comment by drbyte** [comment]
Hmmm, even after fixing this syntax issue, adding `custom-control-input` seems to make `checkboxes` quite difficult to handle.

Maybe should also be adding something like:

```php
if ($p1['type'] === 'checkbox') break;
```

**Comment by zcadditions** [comment]
The template uses bootstraps custom forms. So adding just custom-control-input won't work. The input "check box" itself needs to have a wrapping div.

<div class="custom-control custom-checkbox">
  <input type="checkbox" class="custom-control-input" id="customCheck1">
  <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
</div>

**Comment by drbyte** [comment]
Yes, that works. (must do the label too). Thanks.

Still, the PR fixes an error in the search/replace.

**Comment by zcadditions** [comment]
I agree.

I was torn about the custom inputs in the beginning but thought it gave the forms a polished look.

**Pull request merged**
